services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - spring-boot-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pelindo
      MYSQL_USER: pelindo
      MYSQL_PASSWORD: pelindo
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3310/pelindo?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: pelindo
      SPRING_DATASOURCE_PASSWORD: pelindo
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_URL: jdbc:mysql://host.docker.internal:3310/pelindo?useSSL=false&allowPublicKeyRetrieval=true


volumes:
  mysql-data:

networks:
  spring-boot-mysql-network:
    driver: bridge
